package com.gadarts.te.systems;

public enum SystemEvent {
    SPRITE_TYPE_CHANGED,
    ANIMATION_CHANGED,
    CHARACTER_ANIMATION_RUN_NEW_FRAME,
    CHARACTER_REACHED_NODE,
    USER_CLICKED_NODE,
    PLAYER_REQUESTS_MOVE
}
