package com.gadarts.te

enum class EditorEvents {
    NODES_HEIGHT_SET,
    CLICKED_BUTTON_MODE,
    CLICKED_BUTTON_SAVE,
    CLICKED_BUTTON_LOAD,
    TEXTURE_SELECTED_VIA_GALLERY,
    TEXTURE_SET,
    TEXTURE_SELECTED_FOR_NODES,
    TEXTURE_SELECTED_FOR_WALLS,
    CLICKED_GRID_CELL,
    SCROLLED_UP,
    SCROLLED_DOWN,
    DRAGGED_GRID_CELL,
    ACTION_BEGIN,
    ACTION_TAKE_STEP,
    ACTION_DONE
}
