package com.gadarts.te

enum class EditorEvents {
    MODE_SELECTED,
    TEXTURE_SELECTED,
    CLICKED_GRID_CELL,
    SCROLLED_UP,
    SCROLLED_DOWN,
    DRAGGED_GRID_CELL,
    ACTION_BEGIN,
    ACTION_TAKE_STEP,
    ACTION_DONE
}
