package com.gadarts.te

enum class EditorEvents {
    NODES_HEIGHT_SET,
    CLICKED_BUTTON_MODE,
    CLICKED_BUTTON_SAVE,
    CLICKED_BUTTON_LOAD,
    CLICKED_LEFT_ON_GRID_CELL,
    CLICKED_RIGHT_ON_GRID_CELL,
    CLICKED_TREE_NODE,
    TEXTURE_SELECTED_VIA_GALLERY,
    TEXTURE_SET,
    TEXTURE_SELECTED_FOR_NODES,
    TEXTURE_SELECTED_FOR_WALLS,
    SCROLLED_UP,
    SCROLLED_DOWN,
    DRAGGED_GRID_CELL,
    ACTION_BEGIN,
    ACTION_TAKE_STEP,
    ACTION_DONE,
    MODE_CHANGED
}
